# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 07:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_auto_20170912_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reviewers',
            field=models.ManyToManyField(related_name='review_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 12, 7, 45, 26, 87930, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 12, 7, 45, 26, 89310, tzinfo=utc)),
        ),
    ]
