# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 07:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170912_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleusercomment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleusercomment',
            name='user',
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 12, 7, 46, 1, 225612, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 12, 7, 46, 1, 227353, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='ArticleUserComment',
        ),
    ]
